name: StyLua Formatting
on:
    pull_request:
    push:
        branches: [main]
jobs:
    stylua:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: StyLua Check
              uses: JohnnyMorganz/stylua-action@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  version: latest
                  args: --check .
